# Generated by Django 4.0.5 on 2022-06-29 14:40

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('title', django_mysql.models.ListCharField(models.CharField(max_length=20), max_length=4200, size=200)),
                ('text_data', django_mysql.models.ListCharField(models.CharField(max_length=20000), max_length=4000200, size=200)),
                ('id_data', django_mysql.models.ListCharField(models.CharField(max_length=5), max_length=1200, size=200)),
                ('post_data', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=2200, size=200)),
            ],
        ),
        migrations.CreateModel(
            name='post_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('text_data', models.CharField(max_length=20000)),
                ('id_data', models.CharField(max_length=5)),
            ],
        ),
    ]
