# Generated by Django 4.0.5 on 2022-06-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='list_data',
            field=models.CharField(default='', max_length=400),
        ),
    ]
