# Generated by Django 4.0.5 on 2022-07-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqapp', '0002_data_list_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='type_data',
            field=models.CharField(default='', max_length=400),
        ),
    ]
