# Generated by Django 4.0.5 on 2022-07-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqapp', '0003_data_type_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_data',
            name='type_data',
            field=models.CharField(default='', max_length=1),
        ),
    ]
